--- #YAML:1.0
name:                Unix-Lsof
version:             0.0.7
abstract:            Wrapper to the Unix lsof utility
license:             ~
author:              
    - Marc Beyer <japh@tirwhan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    IPC::Run3:                     0
    Test::More:                    0
    version:                       0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
