# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Unix-Lsof
version:      v0.0.1
version_from: lib/Unix/Lsof.pm
installdirs:  site
requires:
    IPC::Run3:                     0
    Test::More:                    0
    version:                       0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
